# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: certain_lives_org
email: funsworkings@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  portfolio site for artist -> certain lives
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: funsworkings
github_username:  funsworkings

# Build settings
#theme: minima
plugins:
  - jekyll-feed

navigation:
  - title: bandcamp
    url: https://certainlives.bandcamp.com
  - title: instagram
    url: https://www.instagram.com/certain_lives

root_pages:
  - title: about
    url: /about/
  - title: blog
    url: /blog/
  - title: gallery
    url: /gallery/
  - title: '???'
    url: https://www.youtube.com/watch?v=ME64bRiQi24&ab_channel=CNBCPrime

images-url: "/assets/img/"
texts-url: "/assets/txt/"

particles_url: "img/star-child.png"

collections:
  blog:
    output: true
  gallery:
    output: true

# Change this value to adjust all recent posts shown on homepage
recent-items-stack-height: 6

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
